#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions  # Tutorial clean functions

cleanCase
rm -R 0 #remove zero case

# Remove surface and features
rm -rf constant/extendedFeatureEdgeMesh > /dev/null 2>&1
rm -f constant/triSurface/rotatingZone.eMesh > /dev/null 2>&1
rm -f constant/triSurface/fixed.eMesh > /dev/null 2>&1
rm -f 0/pointLevel > /dev/null 2>&1
rm -f 0/cellLevel > /dev/null 2>&1

#create 0 folder
cp -R 0.orig 0

runApplication touch foam.foam
runApplication blockMesh
runApplication topoSet
runApplication decomposePar 
runParallel $(getApplication)
runApplication reconstructPar -latestTime
runApplication postProcess -func linesample -latestTime
mv log.postProcess log.postProcesslineSample
runApplication postProcess -funcs '(writeCellCentres)'
mv log.postProcess log.postProcesswriteCellCentres
runApplication postProcess -func surfaces -latestTime
mv log.postProcess log.postProcesssurfaces
rm -r process*
#------------------------------------------------------------------------------
